"""Compatibility contract with the retired Discord recommendation engine."""

# The Discord cog sorts on its leading symbol: rocket, explosion, cross,
# warning, then speech bubble/informational text. Keep this separate from the
# web severity label so schema/advice remain useful filters in the UI.
DISCORD_PRIORITY_BY_RULE = {
    "plexapi_update": 1, "kometa_update": 1, "plex_security": 1,
    "plex_version": 2, "kometa_critical": 2, "internal_server": 2,
    "yaml": 2, "traceback": 2,
    "anidb_connection": 3, "anidb_auth": 3, "api_key_missing": 3,
    "kometa_error": 3, "image_unreadable": 3, "flixpatrol_parse": 3,
    "flixpatrol_subscription": 3, "image_size": 3, "incomplete_log": 3,
    "mal_connection": 3, "mass_update": 3, "mdblist_attribute": 3,
    "mdblist_api_key": 3, "mdblist_limit": 3, "metadata_attribute": 3,
    "metadata_load": 3, "overlay_load": 3, "playlist_load": 3,
    "omdb_api_key": 3, "omdb_limit": 3, "overlay_font": 3,
    "overlay_image": 3, "playlist_library": 3, "plex_library": 3,
    "plex_url": 3, "tautulli_key": 3, "tautulli_url": 3, "tmdb_key": 3,
    "timeout": 3, "tmdb_connection": 3, "service_config": 3,
    "trakt_connection": 3, "db_cache_exceeds_memory": 3,
    "schedule_over_24_hours": 3, "schedule_overlap": 3,
    "schedule_conflict": 3, "schedule_maintenance_buffer": 3,
    "checkfiles": 4, "legacy_other_award": 4, "kometa_warning": 4,
    "legacy_delete_unmanaged": 4, "linuxserver": 4, "legacy_missing": 4,
    "plex_no_items": 4, "overlay_reset": 4, "overlay_existing": 4,
    "legacy_overlay_level": 4, "plex_regex": 4, "rating_rounding": 4,
    "run_order": 4, "memory_overlay_insufficient": 4, "memory_low": 4,
    "memory_overlay_low": 4,
    "cache_disabled": 5, "id_conversion": 5, "legacy_git": 5,
    "legacy_pmm": 5, "wsl_memory": 5, "db_cache_undersized": 5,
    "memory_unavailable": 5, "schedule_unavailable": 5,
}

# Every active Discord branch and helper outcome has an explicit web owner.
# Multiple helper outcomes intentionally map to separate structured web IDs.
DISCORD_BRANCH_TO_RULE = {
    "anidb69_errors": "anidb_connection",
    "anidb_auth_errors": "anidb_auth",
    "api_blank_errors": "api_key_missing",
    "bad_version_found_errors": "plex_version",
    "cache_false": "cache_disabled",
    "checkFiles": "checkfiles",
    "other_award": "legacy_other_award",
    "critical_errors": "kometa_critical",
    "error_errors": "kometa_error",
    "warning_errors": "kometa_warning",
    "convert_errors": "id_conversion",
    "corrupt_image_errors": "image_unreadable",
    "delete_unmanaged_collections_errors": "legacy_delete_unmanaged",
    "flixpatrol_errors": "flixpatrol_parse",
    "flixpatrol_paywall": "flixpatrol_subscription",
    "git_kometa_errors": "legacy_git",
    "pmm_legacy_errors": "legacy_pmm",
    "image_size": "image_size",
    "incomplete_message": "incomplete_log",
    "internal_server_errors": "internal_server",
    "lsio_errors": "linuxserver",
    "mal_connection_errors": "mal_connection",
    "mass_update_errors": "mass_update",
    "mdblist_attr_errors": "mdblist_attribute",
    "mdblist_errors": "mdblist_api_key",
    "mdblist_api_limit_errors": "mdblist_limit",
    "metadata_attribute_errors": "metadata_attribute",
    "metadata_load_errors": "metadata_load",
    "overlay_load_errors": "overlay_load",
    "playlist_load_errors": "playlist_load",
    "missing_path_errors": "legacy_missing",
    "new_version_found_errors": "kometa_update",
    "new_plexapi_version_found_errors": "plexapi_update",
    "no_items_found_errors": "plex_no_items",
    "omdb_errors": "omdb_api_key",
    "omdb_api_limit_errors": "omdb_limit",
    "overlays_bloat": "overlay_reset",
    "overlay_font_missing": "overlay_font",
    "overlay_apply_errors": "overlay_existing",
    "overlay_image_missing": "overlay_image",
    "overlay_level_errors": "legacy_overlay_level",
    "playlist_errors": "playlist_library",
    "plex_lib_errors": "plex_library",
    "plex_regex_errors": "plex_regex",
    "plex_url_errors": "plex_url",
    "rounding_errors": "rating_rounding",
    "ruamel_errors": "yaml",
    "run_order_errors": "run_order",
    "security_vuln_hits": "plex_security",
    "traceback_errors": "traceback",
    "tautulli_url_errors": "tautulli_url",
    "tautulli_apikey_errors": "tautulli_key",
    "timeout_errors": "timeout",
    "to_be_configured_errors": "service_config",
    "tmdb_api_errors": "tmdb_key",
    "tmdb_fail_errors": "tmdb_connection",
    "trakt_connection_errors": "trakt_connection",
    "memory_missing": "memory_unavailable",
    "memory_under_4_with_overlays": "memory_overlay_insufficient",
    "memory_under_4_without_overlays": "memory_low",
    "memory_under_8_with_overlays": "memory_overlay_low",
    "db_cache_exceeds_memory": "db_cache_exceeds_memory",
    "db_cache_under_1gb": "db_cache_undersized",
    "wsl_detected": "wsl_memory",
    "schedule_missing": "schedule_unavailable",
    "schedule_over_24_hours": "schedule_over_24_hours",
    "schedule_over_maintenance_buffer": "schedule_maintenance_buffer",
    "schedule_inside_maintenance": "schedule_conflict",
    "schedule_overlaps_maintenance": "schedule_overlap",
}


def discord_priority(rule_id: str) -> int:
    """Return the original Discord sort band for a migrated web rule."""
    return DISCORD_PRIORITY_BY_RULE[rule_id]
